#define KYBER_K 3
#define KYBER_NAMESPACE(s) pqcrystals_kyber768_ref_##s

#define KYBER_N 256
#define KYBER_Q 3329

#define KYBER_SYMBYTES 32
#define KYBER_SSBYTES  32

#define KYBER_POLYBYTES    384
#define KYBER_POLYVECBYTES (KYBER_K * KYBER_POLYBYTES)

#define KYBER_ETA1 2
#define KYBER_ETA2 2

/* ML-KEM-768: du=10, dv=4 */
#define KYBER_POLYCOMPRESSEDBYTES     128
#define KYBER_POLYVECCOMPRESSEDBYTES  (KYBER_K * 320)

/* PK uses 12-bit compression */
#define KYBER_PKCOMPRESSEDBYTES       (KYBER_K * 384)

#define KYBER_INDCPA_MSGBYTES       (KYBER_SYMBYTES)
#define KYBER_INDCPA_PUBLICKEYBYTES (KYBER_PKCOMPRESSEDBYTES + KYBER_SYMBYTES)
#define KYBER_INDCPA_SECRETKEYBYTES (KYBER_POLYVECBYTES)
#define KYBER_INDCPA_BYTES          (KYBER_POLYVECCOMPRESSEDBYTES + KYBER_POLYCOMPRESSEDBYTES)

#define KYBER_PUBLICKEYBYTES  (KYBER_INDCPA_PUBLICKEYBYTES)
#define KYBER_SECRETKEYBYTES  (KYBER_INDCPA_SECRETKEYBYTES + KYBER_INDCPA_PUBLICKEYBYTES + 2*KYBER_SYMBYTES)
#define KYBER_CIPHERTEXTBYTES (KYBER_INDCPA_BYTES)
