with open('/opt/fibemate-full/www/index.html', 'r') as f:
    h = f.read()
print('len:', len(h))
print('tsa.cn:', 'tsa.cn' in h)
print('disclaimer:', 'disclaimer.html' in h)
print('kat_fips:', 'kat_fips.js' in h)
print('fips203:', 'fips203_verify.js' in h)
print('KAT timeline:', 'KAT/FIPS Verification' in h)
print('ff8c00:', '#ff8c00' in h)
print('05-20 PQ:', 'double-ratchet-pq' in h)
print('05-21 SM2:', 'test_sm2.js' in h)
print('Integration:', 'Integration Milestones' in h)
print('7c8aff:', '#7c8aff' in h)