#!/usr/bin/env node
// SPDX-License-Identifier: GPL-3.0-only
/**
 * FIBEMATE PQC Fuzz Harness Generator
 *
 * Auto-discovers PQC API surfaces and generates jazzer.js-compatible fuzz harnesses.
 *
 * Usage:
 *   node tools/fuzz-harness-generator/generate.cjs
 *   (runs on all known PQC packages inside packages/)
 *
 * Output: fuzz/harness-<pkg>-<func>.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const FUZZ_DIR = path.join(ROOT, 'fuzz');

// ── Known PQC packages ────────────────────────────────────────────────────

const TARGETS = [
  {
    name: 'pqc-kem',
    dir: 'packages/pqc-kem',
    entry: 'index.js',
    isESM: false,
    exports: [
      { func: 'generateKeypair', params: [],           type: 'keygen' },
      { func: 'encapsulate',     params: ['publicKey'], sizes: [1184] },
      { func: 'decapsulate',     params: ['secretKey','ciphertext'], sizes: [2400, 1088] },
      { func: 'compress',        params: ['x','d'],     sizes: [256, 2] },
      { func: 'decompress',      params: ['y','d'],     sizes: [256, 2] },
      { func: 'byteEncode',      params: ['v','d'],     sizes: [256, 2] },
      { func: 'byteDecode',      params: ['buf','d'],   sizes: [256, 2] },
      { func: 'modAdd',          params: ['a','b'],     sizes: [256, 256] },
      { func: 'modSub',          params: ['a','b'],     sizes: [256, 256] },
      { func: 'modMul',          params: ['a','b'],     sizes: [256, 256] },
      { func: 'sha3_256',        params: ['input'],      sizes: [64] },
      { func: 'sha3_512',        params: ['input'],      sizes: [64] },
      { func: 'shake128',        params: ['input','outLen'], sizes: [64, 2] },
      { func: 'shake256',        params: ['input','outLen'], sizes: [64, 2] },
    ],
  },
  {
    name: 'fml-dsa',
    dir: 'packages/fml-dsa',
    entry: 'src/index.js',
    isESM: true,
    // Each ML-DSA instance has keygen(s), sign(m,sig), verify(s,m,pk)
    exports: [
      { func: 'ml_dsa44', type: 'ml-dsa-instance', params: ['seed','msg'], sizes: [32, 64] },
      { func: 'ml_dsa65', type: 'ml-dsa-instance', params: ['seed','msg'], sizes: [32, 64] },
      { func: 'ml_dsa87', type: 'ml-dsa-instance', params: ['seed','msg'], sizes: [32, 64] },
    ],
  },
];

// ── Templates ───────────────────────────────────────────────────────────────

function genPkgRequire(target) {
  const importPath = '../' + path.join(target.dir, target.entry).replace(/\\/g, '/');
  if (target.isESM) {
    return `const pkg = await import('${importPath}');`;
  }
  return `const pkg = require('${importPath}');`;
}

function genCommonGuard(dataParams, totalSize) {
  let code = `  if (data.length < ${totalSize}) return;\n`;
  let offset = 0;
  dataParams.forEach((p, i) => {
    const sz = p.size;
    code += `  const ${p.name} = new Uint8Array(data.slice(${offset}, ${offset + sz}));\n`;
    offset += sz;
  });
  return code;
}

function genHarnessKeygen(target, exp) {
  const lines = [
    '// SPDX-License-Identifier: GPL-3.0-only',
    `// Auto-generated fuzz harness for ${target.name}.${exp.func}`,
    '// Generated by tools/fuzz-harness-generator/generate.cjs',
    '',
    '// @jazzer.js/fuzz',
    '',
    genPkgRequire(target),
    '',
    'module.exports.fuzz = function (data) {',
    '  try {',
    '    const keys = pkg.generateKeypair();',
    '    if (!keys.publicKey || !keys.secretKey) return;',
    '    // Roundtrip: encaps then decaps',
    '    const ct = pkg.encapsulate(keys.publicKey);',
    '    if (!ct.ciphertext) return;',
    '    const ss = pkg.decapsulate(keys.secretKey, ct.ciphertext);',
    '    if (Buffer.isBuffer(ss) && ss.length === 0) return;',
    '    // Invariant: shared secrets must match on valid keypairs',
    '    if (Buffer.isBuffer(ct.sharedSecret) && Buffer.isBuffer(ss)) {',
    '      if (!ct.sharedSecret.equals(ss)) {',
    '        throw new Error(\'KEM invariant: ss mismatch\');',
    '      }',
    '    }',
    '  } catch (e) { /* expected from fuzzer noise */ }',
    '};',
  ];
  return lines.join('\n') + '\n';
}

function genHarnessMLDSA(target, exp) {
  const lines = [
    '// SPDX-License-Identifier: GPL-3.0-only',
    `// Auto-generated fuzz harness for ${target.name}.${exp.func}`,
    '// Generated by tools/fuzz-harness-generator/generate.cjs',
    '',
    '// @jazzer.js/fuzz',
    '',
    genPkgRequire(target),
    '',
    `// Fuzz the ${exp.func} instance: keygen(seed) → sign(msg, sk) → verify(sig, msg, pk)`,
    'export function fuzz(data) {',
    '  if (data.length < 96) return;',
    '  try {',
    `    const seed = new Uint8Array(data.slice(0, 32));`,
    `    const msg = new Uint8Array(data.slice(32, 96));`,
    `    const keys = pkg.${exp.func}.keygen(seed);`,
    '    if (!keys || !keys.publicKey) return;',
    `    const sig = pkg.${exp.func}.sign(msg, keys.secretKey);`,
    '    if (!sig) return;',
    `    const ok = pkg.${exp.func}.verify(sig, msg, keys.publicKey);`,
    '    // Invariant: fresh keygen → sign → verify must succeed',
    '    if (!ok) throw new Error(\'ML-DSA invariant: verify failed on fresh sig\');',
    '  } catch (e) { /* expected */ }',
    '}',
  ];
  return lines.join('\n') + '\n';
}

function genHarnessBuffer(target, exp) {
  const totalSize = exp.sizes.reduce((a, b) => a + b, 0);
  const dataParams = exp.params.map((name, i) => ({ name, size: exp.sizes[i] }));
  const args = dataParams.map(p => p.name).join(', ');

  const lines = [
    '// SPDX-License-Identifier: GPL-3.0-only',
    `// Auto-generated fuzz harness for ${target.name}.${exp.func}`,
    '// Generated by tools/fuzz-harness-generator/generate.cjs',
    '',
    '// @jazzer.js/fuzz',
    '',
    genPkgRequire(target),
    '',
    'module.exports.fuzz = function (data) {',
    genCommonGuard(dataParams, totalSize),
    '  try {',
    `    pkg.${exp.func}(${args});`,
    '  } catch (e) { /* expected */ }',
    '};',
  ];
  return lines.join('\n') + '\n';
}

// ── Main ────────────────────────────────────────────────────────────────────

function main() {
  console.log('\n╔══════════════════════════════════════╗');
  console.log('║  FIBEMATE PQC Fuzz Harness Generator ║');
  console.log('╚══════════════════════════════════════╝\n');

  fs.mkdirSync(FUZZ_DIR, { recursive: true });

  let total = 0;

  for (const target of TARGETS) {
    const pkgJson = JSON.parse(
      fs.readFileSync(path.join(ROOT, target.dir, 'package.json'), 'utf8')
    );
    console.log(`📦 ${pkgJson.name} (${target.isESM ? 'ESM' : 'CJS'})`);

    for (const exp of target.exports) {
      let code;
      if (exp.type === 'keygen' || exp.func === 'generateKeypair') {
        code = genHarnessKeygen(target, exp);
      } else if (exp.type === 'ml-dsa-instance') {
        code = genHarnessMLDSA(target, exp);
      } else {
        code = genHarnessBuffer(target, exp);
      }

      const safeName = exp.func.replace(/\./g, '-');
      const ext = target.isESM ? '.mjs' : '.js';
      const harnessPath = path.join(FUZZ_DIR, `harness-${target.name}-${safeName}${ext}`);
      fs.writeFileSync(harnessPath, code, 'utf8');
      console.log(`  ✅ ${path.relative(ROOT, harnessPath)}`);
      total++;
    }
  }

  console.log(`\n  Done. ${total} harnesses generated in ${path.relative(ROOT, FUZZ_DIR)}/`);
}

main();