/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const lgv2_bind_kem: (a: number, b: number, c: number, d: number) => [number, number];
export const lgv2_confuse: (a: number, b: number, c: bigint) => [number, number];
export const lgv2_confuse_d: (a: number, b: number, c: bigint, d: number) => [number, number];
export const lgv2_confuse_ex: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv2_confuse_full: (a: number, b: number, c: bigint, d: bigint, e: number, f: number, g: number) => [number, number];
export const lgv2_deconfuse: (a: number, b: number, c: bigint) => [number, number];
export const lgv2_deconfuse_d: (a: number, b: number, c: bigint, d: number) => [number, number];
export const lgv2_deconfuse_ex: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv2_deconfuse_full: (a: number, b: number, c: bigint, d: bigint, e: number, f: number, g: number) => [number, number];
export const lgv2_version: () => [number, number];
export const lgv3_active_dim: () => number;
export const lgv3_audit_log: (a: number, b: bigint, c: number) => [number, number];
export const lgv3_confuse_mix: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_deconfuse_mix: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_defense_configure: (a: number, b: number) => number;
export const lgv3_defense_status: () => [number, number];
export const lgv3_diffuse: (a: number, b: number, c: bigint, d: bigint) => [number, number];
export const lgv3_diffuse_inverse: (a: number, b: number, c: bigint, d: bigint) => [number, number];
export const lgv3_dynamic_path_profile: (a: bigint) => [number, number];
export const lgv3_opaque_check: (a: number, b: bigint) => number;
export const lgv3_opaque_families: () => [number, number];
export const lgv3_opaque_program_cfg: (a: bigint, b: bigint, c: number) => [number, number];
export const lgv3_pipeline_bytecode: (a: bigint, b: bigint, c: number) => [number, number];
export const lgv3_pipeline_bytecode_inverse: (a: bigint, b: bigint, c: number) => [number, number];
export const lgv3_pipeline_deobfuscate: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_pipeline_deobfuscate_dynamic: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_pipeline_obfuscate: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_pipeline_obfuscate_dynamic: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_rand_seed: (a: bigint, b: bigint, c: number) => [number, number];
export const lgv3_sealed_deobfuscate: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_sealed_obfuscate: (a: number, b: number, c: bigint, d: bigint, e: number) => [number, number];
export const lgv3_session_diff_ratio: (a: number, b: number, c: bigint, d: bigint, e: bigint, f: number) => number;
export const lgv3_verify_invertibility: (a: bigint) => number;
export const lgv2_unbind_kem: (a: number, b: number, c: number, d: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
