name: Repolinter
permissions: read-all

on: [push, pull_request]

jobs:
  repolinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: todogroup/repolinter-action@4d478dcd860571382da7d512d6dc6dd5f554fbb2
        with:
          config_file: repolinter.json