name: Repolinter
permissions: read-all

on: [push, pull_request]

jobs:
  repolinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: todogroup/repolinter-action@4d478dcd860571382da7d512d6dc6dd5f554fbb2
        with:
          repolinter_rules: |
            "rules":
              "readme-file-exists": {"level": "error"}
              "license-file-exists": {"level": "error"}
              "contributing-file-exists": {"level": "warning"}
              "code-of-conduct-file-exists": {"level": "warning"}
              "changelog-file-exists": {"level": "warning"}
              "security-file-exists": {"level": "error"}
              "support-file-exists": {"level": "off"}
              "readme-references-license": {"level": "warning"}