name: OpenSSF Scorecard
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: [main]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run scorecard
        run: |
          curl -sSL https://github.com/ossf/scorecard/releases/download/v5.1.1/scorecard_5.1.1_linux_amd64.tar.gz | tar xz
          ./scorecard --repo=github.com/Lennonhaha/fibemate --format=sarif --output=results.sarif \
            --publish=false
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5