name: OpenSSF Scorecard
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: [main]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run scorecard
        run: |
          go install github.com/ossf/scorecard/v5@latest
          scorecard --repo=github.com/Lennonhaha/fibemate --format=sarif --output=results.sarif
      - uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5